### ISSUE TITLE
Optimizar el icono del menú hamburguesa

### ISSUE THREAD

**Issue by AngelGuerra** [ardillan/asociacion-reciclate-ya#11]
New pijada is comming...

El icono del menú hamburguesa, tiene un tamaño de 200x200 cuando en realidad se utiliza uno de 25x25, tendiendo en cuenta una pantalla con una densidad de píxeles muy tocha, cuanto sería lo máximo, ¿75x75?

Optimizar esa imagen para ahorrar la friolera de unos bytes.

**Comment by ardillan** [comment]
Lo cierro, todo está híper-deprecado #ardiTheIssuesKiller
