### ISSUE TITLE
Optimizar imagen "foto-grupo" de la página principal

### ISSUE THREAD

**Issue by AngelGuerra** [ardillan/asociacion-reciclate-ya#2]
En la home hay una imagen que no está optimizada y pesa 4,12 MB, optimizar los tamaños de la misma.

![image](https://user-images.githubusercontent.com/7241024/83998834-bd3c7800-a961-11ea-8db5-e0f853a9144f.png)

**Comment by ardillan** [comment]
Qué loco, tienes razón. Voy a investigar el [componente imagen](https://docs.frontity.org/api-reference-1/frontity-components#image) que viene por defecto en Frontity. 

De todas formas, también trataré la imagen para que no ocupe tanto, ni en dimensiones ni en peso.
