### ISSUE TITLE
Corregir scroll horizontal debido al footer

### ISSUE THREAD

**Issue by AngelGuerra** [ardillan/asociacion-reciclate-ya#3]
Hay un scroll horizontal que creo que se debe al footer, en todos los tamaños, pero se hace más evidente cuando el ancho es menor de 900 (que es el tamaño fijo del footer) y el salto al layout _mobile_

![image](https://user-images.githubusercontent.com/7241024/83999162-769b4d80-a962-11ea-9e3e-6e9cdb3518a2.png)

**Comment by ardillan** [comment]
Tienes razón, no debería funcionar de esa manera. El conflicto tiene que ver con los puntos de corte donde la disposición de la página no es del todo coherente con el ancho general del contenedor.

**Comment by ardillan** [comment]
Lo cierro, todo está híper-deprecado #ardiTheIssuesKiller
