### ISSUE TITLE
Centrar siempre el contenido de las cajitas del footer

### ISSUE THREAD

**Issue by AngelGuerra** [ardillan/asociacion-reciclate-ya#6]
Cuanto el texto que contienen las cajitas del footer no llega al final, los títulos no se centran correctamente y quedan ladeados.

![image](https://user-images.githubusercontent.com/7241024/83999729-97b06e00-a963-11ea-8908-32c94597ace2.png)

**Comment by ardillan** [comment]
Bien visto, nada que `flex` no pueda solucionar. 😄

**Comment by ardillan** [comment]
¡Hecho! Lo cierro. Se puede ver en https://github.com/ardillan/asociacion-reciclate-ya/commit/1b9ba3fdd729fbc37309528dc17da603e370062a
