### ISSUE TITLE
Corregir el contenido de prueba de algunas secciones

### ISSUE THREAD

**Issue by AngelGuerra** [ardillan/asociacion-reciclate-ya#7]
Supongo que esto no depende del desarrollador, pero el contenido de las secciones:

- ¿Cómo puedo formar parte?
- ¿Cómo puedo colaborar?
- Actividades que realizamos

Son Lorem Ipsum y el Quijote.

**Comment by ardillan** [comment]
¡Sí! Bien visto 👏. Ya está actualizado. 

Los editores ya tienen constancia de ello. Se han añadido textos que, aunque no son los definitivos, no dan el aspecto de ser una página en desarrollo.
