### ISSUE TITLE
Extender todos los separadores hasta el límite de la pantalla

### ISSUE THREAD

**Issue by AngelGuerra** [ardillan/asociacion-reciclate-ya#8]
Opinión: Molaría que al igual que llegan las waves de separación a la izquierda de la pantalla, también llegaran a la derecha, ¿no?

Véase el separador de la persona que no llega a la derecha de la pantalla.

![image](https://user-images.githubusercontent.com/7241024/84000203-887df000-a964-11ea-9f50-653c159980ac.png)

**Comment by ardillan** [comment]
En teoría debería ir así. Al ser el [mismo componente](https://github.com/ardillan/asociacion-reciclate-ya/blob/master/packages/reciclateya-theme/src/components/structure/Separator.js) se trata de diferente manera los estilos, [dependiendo de las propiedades](https://github.com/ardillan/asociacion-reciclate-ya/blob/master/packages/reciclateya-theme/src/components/structure/Separator.js#L6) que obtenga.

Decidí dejarlo así porque estuve un rato sin dar con el resultado esperado. Echaré un vistazo con más detenimiento, no obstante lo marco con la etiqueta `Necesito ayuda`por si alguien puede echarme una mano.

**Comment by AngelGuerra** [comment]
Echando un vistazo rápido, uno de los problemas es el posicionamiento, en esta línea `${position === "left" ? "left: calc(-50vw);" : "right: 0;"}` dice que si es izquierda (la bici) -50vw y si es derecha (la persona) 0. Una prueba rápida poniendo `right: -50vh;` hace que se extienda la línea (pero se extiende de más y hace que haya scroll), así que por ahí irán los tiros.

Solución que se me ocurre al body ponerle `overflow-x: hidden;` y a las líneas `right: -50vh;`

**Comment by AngelGuerra** [comment]
Otra opción puede ser jugar con el ancho en vez de con la posición, es decir, hacer algo así: `width: calc(50vw - 50px);` donde 50px es la anchura de la personita, pero también habría que probarlo :man_shrugging:

**Comment by ardillan** [comment]
Finalmente he conseguido corregirlo posicionando bien los contenedores, que eran quienes hacían que los separadores no se visualizasen correctamente.
